### ISSUE TITLE
`tree_metrics` for disconnected structures is not reliable

### ISSUE THREAD

**Issue by thomashay** [aidanmorales/rTwig#18]
Hello again, I hope you are having a great new year so far!
Unfortunately, I am encountering some issues with the new `verify = F`-feature you kindly added to `tree_metrics` last month. 
The QSM I provided you for testing appears to be a somehow non-standard one, I cannot apply the function to 90% of my filtered QSMs. I get the error:

```
Calculating Tree Metrics
Generating Point Cloud
Calculating Crown Metrics
Error in if (branch$diameter_base_cm[order[i]]/100 > d && HL[order[i]] >  : 
  missing value where TRUE/FALSE needed
```

I attached some different filtered QSM cylinder data which throws this error. I hope I am not too annoying with my flood of issues ;)
[new_qsm.zip](https://github.com/user-attachments/files/18334195/new_qsm.zip)
Best regards!

**Comment by aidanmorales** [comment]
@thomashay, no worries. These are exceptions I wouldn't be able to find on my own. I'll take a look at this later this week.

**Comment by aidanmorales** [comment]
@thomashay, I pushed a fix for this issue. Filtered QSMs nearly always remove branch cylinders that are used in the crown base calculations, which explains why most, but not all of your QSMs failed with `tree_metrics()`. Connected QSMs never have missing cylinders, so I never had to account for NA values before. Let me know if this works, and as always let me know if there are any other issues of features you might find useful.

**Comment by thomashay** [comment]
Hi, thanks for the fix. I now works in the majority of cases, but I still encounter the same error sometimes. I attached a new QSM which throws the error. 

Have a nice weekend!

[another_qsm.zip](https://github.com/user-attachments/files/18457468/another_qsm.zip)

**Comment by aidanmorales** [comment]
Please try the latest development version. It _should_ fix this issue for good.

**Comment by thomashay** [comment]
Thanks again for the improvement, but I still have two QSMs where the error occurs. I attached both of them.
Best regards!

[last_two.zip](https://github.com/user-attachments/files/18478287/last_two.zip)

**Comment by aidanmorales** [comment]
The third time is the charm! The cylinder gaps occur in both branch order and branch id, meaning these NA values both have to be accounted for when selecting the candidate branch base. In your data, these NA values did not occur consistently, which is why I had to fix this on a tree-by-tree basis. The fix should be general enough to work across all trees, so let me know if it works for you.

**Comment by thomashay** [comment]
@aidanmorales , thanks for the fix!
I now have no issues with TreeQSM and SimpleForest data.
For Treegraph however, I encounter a new error: 

```
Error in `[<-.data.table`(`*tmp*`, 2:(n + 1), 2, value = c(NA, 0.00291999999999999,  : 
  Supplied 3 items to be assigned to 1 items of column 'diameter_cm'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
```

I again attached a QSM producing this error. I occurs for almost all my Treegraph QSMs.
Admittedly, this is an extremely low-quality QSM, but I feel like this should not influence things.

Best regards and have a nice weekend!

[tg_t15.zip](https://github.com/user-attachments/files/18537811/tg_t15.zip)

**Comment by aidanmorales** [comment]
@thomashay: this issue had to do with main stem taper and is not really a bug. When you filtered the data for the Treegraph QSMs, there was only one main stem cylinder remaining, so it was not possible to calculate taper, hence the error message. I added a warning that says that main stem taper can't be calculated just to be clear and explicit. As always, please try out the fix and let me know if you have any further issues.

**Comment by thomashay** [comment]
@aidanmorales , thanks for the improvement! There is yet again a new issue with some Treegraph QSMs:

```
Error in igraph::permute(child_g, match(igraph::V(child_g)$name, id)) : 
  At vendor/cigraph/src/operators/permute.c:50 : Invalid index in permutation vector. Invalid value
```
New test QSM as usually attached...

[tg_t10.zip](https://github.com/user-attachments/files/18558634/tg_t10.zip)

Best regards!

**Comment by aidanmorales** [comment]
@thomashay: I looked into this, and this error is not a bug in `tree_metrics()` or with `igraph`. As the error message says, when trying to find the parent-child connectivity, there are some invalid indices, likely due to missing values from filtering the QSM. 

There are a couple of things to think about here.  Does this error occur if you run `tree_metrics()` without filtering the QSM? If so, I will need the Treegraph `.json` file to check if there are any problems with the QSM or cylinder indices. If not, I might suggest setting the variables of the cylinders you want to filter out to 0 instead of removing them. This will ensure the connectivity of the QSM, but not affect the summaries. For example, setting radius, length, or any variable for that matter should fulfil what you are trying to do. 

Let me know what happens, and we can go from there.

**Comment by thomashay** [comment]
@aidanmorales Thanks for the input and sorry for the late reply. 
I think you are right that setting the cylinder variables will be sufficient for my purposes, that's a good idea in general that I didn't think of. Treegraph data is not so crucial for me at the moment anyways, I might come back to this at some point.
As always thank you and enjoy your weekend!
